name: Organization NodeJS CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
    MONGO_URI: ${{ secrets.MONGO_URI }}
    MONGO_USERNAME:  ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD:  ${{ secrets.MONGO_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup NodeJS Version
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test --if-present

      - name: Install Dependencies
        continue-on-error: true
        run: npm run coverage --if-present
